///ini_view();
room_set_view(room0,0,1,0,0,DW,DH,0,0,DW,DH,0,0,0,0,-1);
globalvar VIEW_OBJECT, VIEW_MOUSE_X, VIEW_MOUSE_Y, VIEW_X_MIN, VIEW_Y_MIN;
VIEW_MOUSE_X = 0;
VIEW_MOUSE_Y = 0;
VIEW_X_MIN = -2500;
VIEW_Y_MIN = 2500;
VIEW_OBJECT = -1;
